#!/usr/bin/env python3
"""
Trading Bot Setup Wizard

Interactive setup for stock bot features.

Run: python setup.py
"""

import os
from pathlib import Path
from typing import Optional


def prompt(question: str, default: Optional[str] = None) -> str:
    """Prompt user for input."""
    if default:
        q = f"{question} [{default}]: "
    else:
        q = f"{question}: "
    
    answer = input(q).strip()
    return answer or default or ""


def prompt_yes_no(question: str, default: bool = True) -> bool:
    """Prompt user for yes/no."""
    default_str = "Y/n" if default else "y/N"
    answer = input(f"{question} [{default_str}]: ").strip().lower()
    
    if answer in ["yes", "y"]:
        return True
    elif answer in ["no", "n"]:
        return False
    else:
        return default


def validate_api_key(key: str) -> bool:
    """Validate API key format."""
    return bool(key) and len(key) >= 10


def validate_webhook(url: str) -> bool:
    """Validate Discord webhook URL."""
    return bool(url) and url.startswith("https://discordapp.com/api/webhooks/")


def setup():
    """Run interactive setup."""
    print("\n" + "="*60)
    print("  🚀 TRADING BOT SETUP WIZARD")
    print("="*60 + "\n")
    
    # Check if .env exists
    env_file = Path(".env")
    if env_file.exists():
        print("✅ .env file found")
        if not prompt_yes_no("Reconfigure?.env?", default=False):
            print("Skipping .env configuration")
            return
    else:
        print("📝 Creating .env file...")
    
    print("\n1️⃣  STOCK TRADING (ALPACA)\n")
    alpaca_key = prompt(
        "Alpaca API Key (get at https://app.alpaca.markets)",
        default=os.getenv("ALPACA_API_KEY", "")
    )
    
    if not validate_api_key(alpaca_key):
        print("❌ Invalid API key")
        return
    
    alpaca_secret = prompt(
        "Alpaca API Secret",
        default=os.getenv("ALPACA_API_SECRET", "")
    )
    
    if not validate_api_key(alpaca_secret):
        print("❌ Invalid secret")
        return
    
    print("\n2️⃣  DISCORD ALERTS - Optional\n")
    discord_webhook = ""
    if prompt_yes_no("Set up Discord webhook?"):
        discord_webhook = prompt(
            "Discord Webhook URL (https://discordapp.com/api/webhooks/...)",
            default=os.getenv("DISCORD_WEBHOOK_URL", "")
        )
        
        if discord_webhook and not validate_webhook(discord_webhook):
            print("⚠️  Warning: Webhook URL looks invalid, but continuing...")
    
    print("\n3️⃣  TRADING CONFIG\n")
    
    min_ai_confidence = prompt(
        "Min AI Confidence (0.0-1.0)",
        default=os.getenv("STOCK_MIN_AI_CONFIDENCE", "0.45")
    )
    
    max_daily_loss = prompt(
        "Max Daily Loss %",
        default=os.getenv("STOCK_MAX_DAILY_LOSS", "0.05")
    )
    
    max_positions = prompt(
        "Max Open Positions",
        default=os.getenv("STOCK_MAX_OPEN_POS", "2")
    )
    
    min_trade = prompt(
        "Min Trade Size ($)",
        default=os.getenv("STOCK_MIN_TRADE_AMOUNT", "10")
    )
    
    print("\n4️⃣  LOGGING\n")
    
    log_level = prompt(
        "Log Level (DEBUG/INFO/WARNING/ERROR)",
        default=os.getenv("STOCK_LOG_LEVEL", "INFO")
    )
    
    # Build .env content
    env_content = f"""# Trading Bot Configuration
# Auto-generated by setup.py

# Stock Trading (Alpaca) - REQUIRED
ALPACA_API_KEY={alpaca_key}
ALPACA_API_SECRET={alpaca_secret}
ALPACA_BASE_URL=https://paper-api.alpaca.markets

# Discord Alerts - Optional
DISCORD_WEBHOOK_URL={discord_webhook}

# Strategy
STOCK_MIN_AI_CONFIDENCE={min_ai_confidence}
STOCK_RSI_OVERSOLD=35
STOCK_RSI_OVERBOUGHT=65

# Risk Management
STOCK_MAX_DAILY_LOSS={max_daily_loss}
STOCK_MAX_OPEN_POS={max_positions}
STOCK_MIN_TRADE_AMOUNT={min_trade}

# Logging
STOCK_LOG_LEVEL={log_level}
"""
    
    # Write .env
    env_file.write_text(env_content)
    print(f"\n✅ .env file created: {env_file}")
    
    print("\n" + "="*60)
    print("✅ SETUP COMPLETE!")
    print("="*60)
    
    print("\nNext steps:")
    print("1. Review .env file (especially API keys)")
    print("2. Run: python cli.py validate-config")
    print("3. Run: python stock_bot.py (main bot)")
    print("4. In another terminal: python dashboard.py (performance)")
    print("\nDocumentation: See GUIDE_PHASE6.md")
    print("")


if __name__ == "__main__":
    try:
        setup()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
